<?php
include 'template/header.phtml';
?>

    <section id="home-section" class="container-fluid home-section"
             style="background-image: url('/Views/images/home-background.png')">
        <div class="home-container">
            <h1>Your Trusted <span style="color: #ff8802;">Auto <br>Repair Experts</span> <br>Since 1978</h1>
            <p>With decades of expertise, we offer premium<br> Continental
                tyres and reliable repairs to keep<br> your journey safe and
                smooth.</p>
            <button type="button" class="btn btn-primary btn-sm custom-button">Book Now</button>
        </div>
    </section>

    <section id="about-section" class="container-fluid about-section"
             style="background-image: url('/Views/images/about-background.png');">
        <div class="container py-5 d-flex align-items-center justify-content-center">
            <div class="text-center about-container">
                <h1 style="color: #ff8802;">About<span style="color: black;"> Us</span></h1>
                <p>
                    "<span style="font-weight: bold">Lien Yiu Battery & Tyre Sdn Bhd</span> has been a trusted car
                    workshop and auto repair shop in Kuala Lumpur since 1978. We specialize in tyre changing, alignment,
                    balancing, foreman repairs, engine overhauls, spare part installation, oil changes, and battery
                    services.
                </p>
                <p>
                    Continental Tyre Malaysia, with over 150 years of industry expertise, is synonymous with premium
                    quality and German technology. Preferred by over 800 car manufacturers, we deliver top-notch service
                    and products. Safety is our utmost priority, ensuring each Continental tyre offers unparalleled
                    grip, stability, and durability. Whether navigating city streets or rugged terrain, our tyres are
                    designed to keep you safe."
                </p>
            </div>
        </div>
    </section>

    <section id="appointment-section" class="container-fluid appointment-section">
        <div class="row align-items-center">
            <!-- Left Column -->
            <div class="col-lg-6 col-md-12 text-lg-start px-0 appointment-container"
                 style="background-image: url('/Views/images/appointment-bg-2.png'); background-size: cover;">
                <div class="p-5">
                    <h1>Make An <br>
                        <span style="color: #ff8802;">Appointment</span></h1>
                    <p>
                        "Fill, Book, Drive – Simple Scheduling <br> and Easy Appointment Checking for <br> your Car
                        Services."
                    </p>
                    <button type="button" class="btn btn-primary btn-sm custom-button me-3 mt-4" data-bs-toggle="modal"
                            data-bs-target="#bookAppointmentModal">Book Now
                    </button>
                    <button type="button" class="btn btn-primary btn-sm custom-button mt-4" data-bs-toggle="modal"
                            data-bs-target="#checkAppointmentModal">Check Booking
                    </button>
                </div>
            </div>
            <!-- Right Column -->
            <div class="col-lg-6 col-md-12 text-center text-lg-start px-0 appointment-container-1"
                 style="background-image: url('/Views/images/appointment-bg-1.png');">
                <div class="p-5">

                </div>
            </div>
        </div>
    </section>

    <section id="#services-section" class="container-fluid services-section"
             style="background-image: url('/Views/images/card-background.png');">
        <div class="container-fluid py-5 d-flex align-items-center justify-content-center">
            <div class="text-center">
                <h1><span style="color:black;">Our</span> Services</h1>
                <div class="row justify-content-center">
                    <div class="col-lg-4 col-md-6 col-sm-12 d-flex justify-content-center">
                        <div class="card">
                            <img src="/Views/images/engine-oil.png" class="card-img-top" alt="Card Image"
                                 loading="lazy">
                            <div class="card-body">
                                <h5 class="card-title">Engine Oil Change</h5>
                                <p class="card-text">Refresh your engine with premium oil for
                                    better performance and durability.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 d-flex justify-content-center">
                        <div class="card">
                            <img src="/Views/images/tyre.png" class="card-img-top" alt="Card Image"
                                 loading="lazy">
                            <div class="card-body">
                                <h5 class="card-title">Tyre Services</h5>
                                <p class="card-text">Expert tyre care for better traction,
                                    safety, and performance.</p>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-12 d-flex justify-content-center">
                        <div class="card">
                            <img src="/Views/images/battery.png" class="card-img-top" alt="Card Image"
                                 loading="lazy">
                            <div class="card-body">
                                <h5 class="card-title">Battery Replacement</h5>
                                <p class="card-text">Reliable battery replacements to keep you
                                    moving without interruptions.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="map-section" class="map-section">
        <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4556.641100327743!2d100.31001447554719!3d5.387818135316846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x304ac17be5a7c43d%3A0x34379efb8200ac8d!2sContinental%20Lien%20Yiu%20Battery%20%26%20Tyre%20Sdn%20Bhd!5e1!3m2!1sen!2smy!4v1733942623864!5m2!1sen!2smy"
            width="100%" height="100%"
            style="border:0;"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade">
        </iframe>
    </section>

    <!-- Modal: Book Appointment -->
    <div class="modal fade" id="bookAppointmentModal" tabindex="-1" aria-labelledby="bookAppointmentModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="bookAppointmentModalLabel">Book Appointment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="mb-3">
                            <label for="fullName" class="form-label">Full Name</label>
                            <input type="text" class="form-control" id="fullName" placeholder="Enter your full name"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="carNumber" class="form-label">Car Number</label>
                            <input type="text" class="form-control" id="carNumber" placeholder="Enter your car number"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="appointmentDate" class="form-label">Date</label>
                            <input type="date" class="form-control" id="appointmentDate" required>
                        </div>
                        <div class="mb-3">
                            <label for="appointmentTime" class="form-label">Time</label>
                            <input type="time" class="form-control" id="appointmentTime" required>
                        </div>
                        <div class="mb-3">
                            <label for="phoneNumber" class="form-label">Phone Number</label>
                            <input type="tel" class="form-control" id="phoneNumber"
                                   placeholder="Enter your phone number" required>
                        </div>
                        <div class="mb-3">
                            <label for="email" class="form-label">Email (Optional)</label>
                            <input type="email" class="form-control" id="email" placeholder="Enter your email">
                        </div>
                        <button type="button" class="btn btn-primary btn-sm custom-button mt-3 mb-3">Confirm</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

    <!-- Modal: Check Appointment -->
    <div class="modal fade" id="checkAppointmentModal" tabindex="-1" aria-labelledby="checkAppointmentModalLabel"
         aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="checkAppointmentModalLabel">Check My Appointment</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <form>
                        <div class="mb-3">
                            <label for="checkFullName" class="form-label">Full Name</label>
                            <input type="text" class="form-control" id="checkFullName"
                                   placeholder="Enter your full name" required>
                        </div>
                        <div class="mb-3">
                            <label for="checkCarNumber" class="form-label">Car Number</label>
                            <input type="text" class="form-control" id="checkCarNumber"
                                   placeholder="Enter your car number" required>
                        </div>
                        <div class="mb-3">
                            <label for="checkPhoneNumber" class="form-label">Phone Number</label>
                            <input type="tel" class="form-control" id="checkPhoneNumber"
                                   placeholder="Enter your phone number" required>
                        </div>
                        <div class="mb-3">
                            <label for="checkEmail" class="form-label">Email (Optional)</label>
                            <input type="email" class="form-control" id="checkEmail" placeholder="Enter your email">
                        </div>
                        <button type="button" class="btn btn-primary btn-sm custom-button mt-3 mb-3">Check</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

<?php
include 'template/footer.phtml';
?>