<?php
include 'template/header.phtml';
?>

<div id="homeCarousel" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-inner">
        <!-- Slide 1 -->
        <div class="carousel-item active">
            <section id="home-section" class="container-fluid home-section"
                     style="background-image: url('/Views/images/home-background.png')">
                <div class="home-container">
                    <h1>Your Trusted <span style="color: #ff8802;">Auto <br>Repair Experts</span> <br>Since 1978</h1>
                    <p>With decades of expertise, we offer premium<br> Continental
                        tyres and reliable repairs to keep<br> your journey safe and
                        smooth.</p>
                    <a href="index.php?page=home#services-section" class="btn btn-primary btn-sm custom-button me-3 mt-4">Our Services
                    </a>
                </div>
            </section>
        </div>

        <!-- Slide 2 -->
        <div class="carousel-item">
            <section id="home-section" class="container-fluid home-section promotion-section-1"
                     style="background-image: url('/Views/images/home-promotion-1.png')">
                <div class="home-container home-promotion-1">
                    <h1>Chinese New Year <br> Special <br> <span style="color: #2f354b;">Tyre & Battery</span></h1>
                    <p>Offer valid from Jan 5 - Feb 5, <b>free installation</b>.<br>
                        Start the new year with a smooth and safe ride!</p>
                    <a href="index.php?page=home#appointment-section" class="btn btn-primary btn-sm custom-button me-3 mt-4">Book Now</a>
                </div>
            </section>
        </div>

        <!-- Slide 3 -->
        <div class="carousel-item">
            <section id="home-section" class="container-fluid home-section promotion-section-2"
                     style="background-image: url('/Views/images/home-promotion-2.png')">
                <div class="home-container home-promotion-2">
                    <h1>Christmas <br>
                        Special: <span style="color: #2f354b;"> 25% Off  <br>Labour Services</span></h1>
                    <p>Don’t miss this limited-time offer—book  <br> your service today and save big!</p>
                    <a href="index.php?page=home#map-section" class="btn btn-primary btn-sm custom-button me-3 mt-4">Our Location
                        </a>
                </div>
            </section>
        </div>
    </div>

    <!-- Carousel Controls -->
    <button class="carousel-control-prev" type="button" data-bs-target="#homeCarousel" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#homeCarousel" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<section id="services-section" class="container-fluid services-section"
         style="background-image: url('/Views/images/card-background.png');">
    <div class="container-fluid py-5 d-flex align-items-center justify-content-center">
        <div class="text-center">
            <h1><span style="color: #2f354b;">Our</span> Services</h1>
            <div class="row justify-content-center">
                <div class="col-lg-4 col-md-6 col-sm-12 d-flex justify-content-center">
                    <div class="card">
                        <img src="/Views/images/engine-oil.png" class="card-img-top" alt="Card Image"
                             loading="lazy">
                        <div class="card-body">
                            <h5 class="card-title">Engine Oil Change</h5>
                            <p class="card-text">Refresh your engine with premium oil for
                                better performance and durability.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 d-flex justify-content-center">
                    <div class="card">
                        <img src="/Views/images/tyre.png" class="card-img-top" alt="Card Image"
                             loading="lazy">
                        <div class="card-body">
                            <h5 class="card-title">Tyre Services</h5>
                            <p class="card-text">Expert tyre care for better traction,
                                safety, and performance.</p>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 col-md-6 col-sm-12 d-flex justify-content-center">
                    <div class="card">
                        <img src="/Views/images/battery.png" class="card-img-top" alt="Card Image"
                             loading="lazy">
                        <div class="card-body">
                            <h5 class="card-title">Battery Replacement</h5>
                            <p class="card-text">Reliable battery replacements to keep you
                                moving without interruptions.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section id="appointment-section" class="container-fluid appointment-section">
    <div class="row align-items-center">
        <!-- Left Column -->
        <div class="col-lg-6 col-md-12 text-lg-start px-0 appointment-container"
             style="background-image: url('/Views/images/appointment-bg-2.png'); background-size: cover;">
            <div class="p-5">
                <h1>Make An <br>
                    <span style="color: #ff8802;">Appointment</span></h1>
                <p>
                    "Fill, Book, Drive – Simple Scheduling <br> and Easy Appointment Checking for <br> your Car
                    Services."
                </p>
                <button type="button" class="btn btn-primary btn-sm custom-button me-3 mt-4" data-bs-toggle="modal"
                        data-bs-target="#bookAppointmentModal">Book Now
                </button>
                <button type="button" class="btn btn-primary btn-sm custom-button mt-4" data-bs-toggle="modal"
                        data-bs-target="#checkAppointmentModal">Check Booking
                </button>
            </div>
        </div>
        <!-- Right Column -->
        <div class="col-lg-6 col-md-12 text-center text-lg-start px-0 appointment-container-1"
             style="background-image: url('/Views/images/appointment-bg-1.png');">
            <div class="p-5">

            </div>
        </div>
    </div>
</section>

<section id="about-section" class="container-fluid about-section"
         style="background-image: url('/Views/images/about-background.png');">
    <div class="container py-5 d-flex align-items-center justify-content-center">
        <div class="text-center about-container">
            <h1 style="color: #ff8802;">About<span style="color: #2f354b;"> Us</span></h1>
            <p>
                "<span style="font-weight: bold">Lien Yiu Battery & Tyre Sdn Bhd</span> has been a trusted car
                workshop and auto repair shop in Kuala Lumpur since 1978. We specialize in tyre changing, alignment,
                balancing, foreman repairs, engine overhauls, spare part installation, oil changes, and battery
                services.
            </p>
            <p>
                Continental Tyre Malaysia, with over 150 years of industry expertise, is synonymous with premium
                quality and German technology. Preferred by over 800 car manufacturers, we deliver top-notch service
                and products. Safety is our utmost priority, ensuring each Continental tyre offers unparalleled
                grip, stability, and durability. Whether navigating city streets or rugged terrain, our tyres are
                designed to keep you safe."
            </p>
        </div>
    </div>
</section>


<section id="map-section" class="map-section">
    <iframe
            src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4556.641100327743!2d100.31001447554719!3d5.387818135316846!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x304ac17be5a7c43d%3A0x34379efb8200ac8d!2sContinental%20Lien%20Yiu%20Battery%20%26%20Tyre%20Sdn%20Bhd!5e1!3m2!1sen!2smy!4v1733942623864!5m2!1sen!2smy"
            width="100%" height="100%"
            style="border:0;"
            allowfullscreen=""
            loading="lazy"
            referrerpolicy="no-referrer-when-downgrade">
    </iframe>
</section>

<!-- Modal: Book Appointment -->
<div class="modal fade" id="bookAppointmentModal" tabindex="-1" aria-labelledby="bookAppointmentModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100" id="bookAppointmentModalLabel">Book Appointment</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="index.php?page=home" method="POST" id="appointmentForm">
                    <div class="mb-3 d-flex align-items-center">
                        <label for="fullName" class="form-label me-3 field-custom-width">Name</label>
                        <input type="text" class="form-control" id="fullName" name="fullName"
                               placeholder="Enter your name" required>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="carNumber" class="form-label me-3 field-custom-width">Car Number</label>
                        <input type="text" class="form-control" id="carNumber" name="carNumber"
                               placeholder="Enter your car number" required>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="carBrand" class="form-label me-3 field-custom-width">Car Brand</label>
                        <select class="form-select" id="carBrand" name="carBrand" required>
                            <option value="" selected disabled>Select Car Brand</option>
                            <?php foreach ($carBrands as $brand): ?>
                                <option value="<?= htmlspecialchars($brand['brand_id']) ?>">
                                    <?= htmlspecialchars($brand['brand_name']) ?>
                                </option>
                            <?php endforeach; ?>
                        </select>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="carModel" class="form-label me-3 field-custom-width">Car Model</label>
                        <select class="form-select" id="carModel" name="carModel" required>
                            <option value="Select Car Model" selected disabled>Select Car Model</option>
                        </select>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="appointmentDate" class="form-label me-3 field-custom-width">Date</label>
                        <input type="date" class="form-control" id="appointmentDate" name="appointmentDate"
                               required>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="appointmentTime" class="form-label me-3 field-custom-width">Time</label>
                        <input type="time" class="form-control" id="appointmentTime" name="appointmentTime"
                               required>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="phoneNumber" class="form-label me-3 field-custom-width">Phone Number</label>
                        <input type="text" class="form-control" id="phoneNumber" name="phoneNumber"
                               placeholder="Enter your phone number" required>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="email" class="form-label me-3 field-custom-width">Email</label>
                        <input type="email" class="form-control" id="email" name="email"
                               placeholder="Enter your email" required>
                    </div>
                    <div class="mb-3 mt-3">
                        <label for="remark" class="form-label mb-2">Remark (Optional)</label>
                        <textarea class="form-control" id="remark" name="remark" rows="3"
                                  placeholder="e.g., change engine oil, replace tires, check battery."></textarea>
                    </div>
                    <div class="text-center mt-4">
                        <button type="submit" name="appointment" class="btn btn-primary btn-sm custom-button mt-3 mb-3">Confirm
                        </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal: Check Appointment -->
<div class="modal fade" id="checkAppointmentModal" tabindex="-1" aria-labelledby="checkAppointmentModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100" id="checkAppointmentModalLabel">Check My Appointment</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form action="index.php?page=home" method="POST" id="checkAppointmentForm">
                    <div class="mb-3 d-flex align-items-center">
                        <label for="checkFullName" class="form-label field-custom-width">Full Name</label>
                        <input type="text" class="form-control" id="checkFullName"
                               placeholder="Enter your full name" required>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="checkCarNumber" class="form-label field-custom-width">Car Number</label>
                        <input type="text" class="form-control" id="checkCarNumber" name="carNumber"
                               placeholder="Enter your car number" required>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="checkPhoneNumber" class="form-label field-custom-width">Phone Number</label>
                        <input type="text" class="form-control" id="checkPhoneNumber"
                               placeholder="Enter your phone number" required>
                    </div>
                    <div class="mb-3">
                        <label for="" class="form-label ">Or</label>
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="checkEmail" class="form-label field-custom-width">Email</label>
                        <input type="email" class="form-control" id="checkEmail" placeholder="Enter your email">
                    </div>
                    <div class="text-center mt-4">
                        <button type="submit" name="checkBooking" class="btn btn-primary btn-sm custom-button mt-3 mb-3">Check</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Modal: result modal -->
<div class="modal fade" id="resultModal" tabindex="-1" aria-labelledby="resultModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100" id="resultModalLabel">Modal Title</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="resultModalBody">
                    Modal body content goes here.
                </div>
                <div class="text-center mt-4">
                    <button type="button" class="btn btn-primary btn-sm custom-button mt-3 mb-3"
                            data-bs-dismiss="modal" onclick="redirectToSection()">Close
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<!-- Modal: Book Error -->
<div class="modal fade" id="failureModal" tabindex="-1" aria-labelledby="failureModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="failureModalLabel">Appointment Failed</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                Failed to book the appointment. Please try again.
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-primary" data-bs-dismiss="modal" onclick="showBookingModal()">
                    Go Back to Booking
                </button>
            </div>
        </div>
    </div>
</div>

<!-- Modal: View Appointment Confirmation -->
<div class="modal fade" id="confirmationModal" tabindex="-1" aria-labelledby="confirmationModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100" id="confirmationModalLabel">Appointment Confirmation</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <p>Mr/Ms <strong id="confirmationModalName"></strong>, your appointment references number is <strong id="confirmationModalId"></strong>, confirmed with car number
                        <strong id="confirmationModalCarNumber"></strong> on <strong id="confirmationModalDate"></strong>.</p>
                    <p>If you wish to cancel your appointment, click the button below.</p>
                </div>
                <div class="text-center mt-5">
                    <!-- Checkbox Confirmation -->
                    <div id="checkboxConfirmation" class="d-none">
                        <div class="form-check text-start">
                            <input class="form-check-input" type="checkbox" id="confirmCheckbox" style="margin-top: 3px;">
                            <label class="form-check-label" for="confirmCheckbox">
                                I confirm that I want to cancel the appointment.
                            </label>
                        </div>
                        <form id="cancelAppointmentForm" method="POST" action="index.php">
                            <input type="hidden" name="cancelAppointment" value="1"> <!-- This identifies the form action -->
                            <input type="hidden" name="appointmentId" id="appointmentIdInput" value="">
                            <button type="submit" class="btn btn-danger btn-sm custom-button mt-5 mb-3" id="confirmCancel" disabled>
                                Confirm Cancellation
                            </button>
                        </form>


                    </div>
                    <!-- Cancel Button -->
                    <button type="button" class="btn btn-danger btn-sm custom-button mt-2 mb-3" id="cancelButton">
                        Cancel Appointment
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

<?php
include 'template/footer.phtml';
?>
