<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <link rel="stylesheet" href="/Views/css/styles.css">
</head>
<body>
<nav class="navbar navbar-expand-md fixed-top">
    <div class="container-fluid px-5">
        <a class="navbar-brand" href="#">Lien Yiu <br>
            <span>Battery & Tyre Sdn Bhd</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=home#home-section">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=home#about-section">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=home#appointment-section">Appointment</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="index.php?page=home#services-section">Services</a>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">

                <li class="nav-item">
                    <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#loginModal">Login</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

<!-- Modal: Login -->
<div class="modal fade" id="loginModal" tabindex="-1" aria-labelledby="loginModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header text-center">
                <h5 class="modal-title w-100" id="loginModalLabel">Login</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <form>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="username" class="form-label me-3 login field-login-width">Username</label>
                        <input type="text" class="form-control" id="username" placeholder="Enter your username">
                    </div>
                    <div class="mb-3 d-flex align-items-center">
                        <label for="password" class="form-label me-3 login field-login-width">Password</label>
                        <input type="password" class="form-control" id="password" placeholder="Enter your password">
                    </div>
                    <div class="text-center mt-4">
                        <button type="submit" class="btn btn-primary btn-sm custom-button mt-3 mb-3">Login</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>